// woj-react/src/DateComponent/DateComponent.js
import React from 'react'

class DateComponent extends React.Component{

    constructor(props){
        super(props);
    }

    render(){
        var date = "Tänään on " + new Date().toLocaleDateString("fi-FI");
        return (
            <div>{date}</div>
        )
    }
}

export default DateComponent;

// woj-angular/src/app/date/date.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'date',
  templateUrl: './date.component.html',
  styleUrls: ['./date.component.css']
})
export class DateComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  date = "Tänään on " + new Date().toLocaleDateString("fi-FI");

}
